spring:
  config:
    activate:
      on-profile: local

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: nokt
    password: 1234
    url: jdbc:mysql://blog-mysql:3306/blog

  data:
    redis:
      port: 6379
      host: blog-redis
  neo4j:
    authentication:
      username: neo4k
      password: nokt12345678
    uri: bolt://blog-neo4j:7687

  docker:
    compose:
      enabled: true
      file: docker-compose.yml
      host: blog

server:
  port: 8099
  shutdown: graceful

jwt:
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  accessToken-validity-in-seconds: 3600 # 1??
  refreshToken-validity-in-seconds: 18000 # 5??